import { archiveAsset, createAsset, getAssetById, getAssets, restoreAsset, saveAsset, updateAsset } from "./assets";
import type { Asset, AssetStatus, AssetType } from "./types/asset";
import { createSupabaseBrowserClient } from "../supabase/client";
import type { Database } from "../supabase/types";

export type AssetRepositoryListOptions = { type?: AssetType; status?: AssetStatus; sourceKind?: "local" | "external"; limit?: number };
export interface AssetRepository { listAssets(options?: AssetRepositoryListOptions): Promise<Asset[]>; getAsset(assetId: string): Promise<Asset | undefined>; createAsset(input: Omit<Asset, "id" | "createdAt" | "updatedAt">): Promise<Asset>; updateAsset(assetId: string, patch: Partial<Omit<Asset, "id" | "createdAt">>): Promise<Asset | undefined>; archiveAsset(assetId: string): Promise<void>; restoreAsset(assetId: string): Promise<void>; }

function filterAssets(assets: Asset[], options: AssetRepositoryListOptions) { const filtered = assets.filter((asset) => !options.type || asset.type === options.type).filter((asset) => !options.status || asset.status === options.status).filter((asset) => !options.sourceKind || asset.source.kind === options.sourceKind); return options.limit && options.limit > 0 ? filtered.slice(0, options.limit) : filtered; }
export const assetLocalRepository: AssetRepository = { async listAssets(options = {}) { return filterAssets(getAssets(), options); }, async getAsset(id) { return getAssetById(id); }, async createAsset(input) { return createAsset(input); }, async updateAsset(id, patch) { updateAsset(id, patch); return getAssetById(id); }, async archiveAsset(id) { archiveAsset(id); }, async restoreAsset(id) { restoreAsset(id); } };

type AssetRow = Database["public"]["Tables"]["assets"]["Row"];
function mapAsset(row: AssetRow): Asset { return { id: row.id, type: row.type as AssetType, name: row.name, title: row.title ?? undefined, description: row.description ?? undefined, source: { kind: row.source_kind === "external" ? "external" : "local", url: row.url }, mimeType: row.mime_type ?? undefined, fileSize: row.size_bytes ?? undefined, width: row.width ?? undefined, height: row.height ?? undefined, duration: row.duration ?? undefined, altText: row.alt_text ?? undefined, status: row.status as AssetStatus, tags: row.tags ?? [], metadata: (row.metadata ?? {}) as Record<string, unknown>, createdAt: row.created_at, updatedAt: row.updated_at }; }
function assetRow(asset: Asset) { return { id: asset.id, type: asset.type, name: asset.name, title: asset.title ?? null, description: asset.description ?? null, alt_text: asset.altText ?? null, source_kind: asset.source.kind, url: asset.source.url, size_bytes: asset.fileSize ?? null, mime_type: asset.mimeType ?? null, width: asset.width ?? null, height: asset.height ?? null, duration: asset.duration ?? null, metadata: asset.metadata ?? {}, tags: asset.tags ?? [], status: asset.status }; }
export const assetSupabaseRepository: AssetRepository = { async listAssets(options = {}) { let query = createSupabaseBrowserClient().from("assets").select("*").order("created_at", { ascending: true }).order("id", { ascending: true }); if (options.type) query = query.eq("type", options.type); if (options.status) query = query.eq("status", options.status); if (options.sourceKind) query = options.sourceKind === "local" ? query.in("source_kind", ["local", "managed"]) : query.eq("source_kind", "external"); if (options.limit && options.limit > 0) query = query.limit(options.limit); const { data, error } = await query; if (error) throw error; return ((data ?? []) as AssetRow[]).map(mapAsset); }, async getAsset(id) { const { data, error } = await createSupabaseBrowserClient().from("assets").select("*").eq("id", id).maybeSingle(); if (error) throw error; return data ? mapAsset(data as AssetRow) : undefined; }, async createAsset(input) { const now = new Date().toISOString(); const asset = { ...input, id: crypto.randomUUID(), createdAt: now, updatedAt: now } as Asset; const { error } = await createSupabaseBrowserClient().from("assets").insert(assetRow(asset) as never); if (error) throw error; return asset; }, async updateAsset(id, patch) { const current = await this.getAsset(id); if (!current) return undefined; const updated = { ...current, ...patch, id, createdAt: current.createdAt, updatedAt: new Date().toISOString() } as Asset; const { error } = await createSupabaseBrowserClient().from("assets").update(assetRow(updated) as never).eq("id", id); if (error) throw error; return updated; }, async archiveAsset(id) { const { error } = await createSupabaseBrowserClient().from("assets").update({ status: "archived" } as never).eq("id", id); if (error) throw error; }, async restoreAsset(id) { const { error } = await createSupabaseBrowserClient().from("assets").update({ status: "ready" } as never).eq("id", id); if (error) throw error; } };

export type AssetRepositorySource = "local" | "supabase";
export function createAssetRepository(source: AssetRepositorySource = "local"): AssetRepository { return source === "supabase" ? assetSupabaseRepository : assetLocalRepository; }