import type { Lesson } from "../types/lesson";

export const math151Lessons: Lesson[] = [
  {
    id: "math151-real-numbers",
    courseId: "math-151",
    chapterId: "real-number-theory",
    weekId: "math151-week-1",
    title: "Real Numbers",
    description: "Place the real numbers in a structured hierarchy and see why they behave like a complete ordered field.",
    order: 1,
    estimatedMinutes: 12,
    objectives: [
      "Explain how the natural, integer, rational, and real numbers fit together.",
      "Recognize why closure matters in algebraic operations.",
      "Connect order and completeness to the real number line.",
    ],
    blocks: [
      { id: "real-step-1-heading", type: "heading", step: 1, text: "The Number Systems", level: 2 },
      { id: "real-step-1-text", type: "text", step: 1, body: "Mathematics does not begin with a blank slate. It begins by noticing patterns in counting, measurement, and structure. The key families of numbers nest inside one another." },
      { id: "real-step-1-math", type: "math", step: 1, expression: "\\mathbb{N} \\subset \\mathbb{Z} \\subset \\mathbb{Q} \\subset \\mathbb{R}", display: true },
      { id: "real-step-2-heading", type: "heading", step: 2, text: "Closed Under Operations", level: 2 },
      { id: "real-step-2-text", type: "text", step: 2, body: "If $a, b \in \mathbb{R}$, then $a + b$, $a - b$, $ab$, and $a/b$ (when $b \neq 0$) also lie in $\mathbb{R}$. This closure is exactly what makes algebra work reliably." },
      { id: "real-step-2-callout", type: "callout", step: 2, tone: "info", text: "Our rules are not arbitrary. They are designed to preserve consistency under addition, multiplication, and comparison." },
      { id: "real-step-3-heading", type: "heading", step: 3, text: "Order and Completeness", level: 2 },
      { id: "real-step-3-text", type: "text", step: 3, body: "The real numbers are ordered, which means each number has a clear place on the line. That ordering lets us define inequalities, distances, and continuity." },
      { id: "real-step-3-worked-example", type: "worked-example", step: 3, title: "Comparing fractions", prompt: "Which is larger: $\frac{2}{3}$ or $\frac{3}{5}$?", solution: "Write both with a common denominator: $\frac{2}{3} = \frac{10}{15}$ and $\frac{3}{5} = \frac{9}{15}$. Since $10 > 9$, we have $\frac{2}{3} > \frac{3}{5}$." },
    ],
  },
  {
    id: "math151-argand-plane",
    courseId: "math-151",
    chapterId: "complex-numbers",
    weekId: "math151-week-2",
    title: "The Argand Plane",
    description: "Build the complex plane from the real number line and the imaginary unit.",
    order: 2,
    estimatedMinutes: 15,
    objectives: ["Explain why the imaginary unit creates a second axis.", "Represent a complex number as a point on the Argand plane.", "Interpret modulus and argument geometrically."],
    blocks: [
      { id: "argand-step-1-heading", type: "heading", step: 1, text: "The 1D Number Line", level: 2 },
      { id: "argand-step-1-text", type: "text", step: 1, body: "Until now, numbers have existed on a single, one-dimensional line. The Real Numbers ($\\mathbb{R}$) stretch infinitely left and right." },
      { id: "argand-step-2-heading", type: "heading", step: 2, text: "The Imaginary Unit", level: 2 },
      { id: "argand-step-2-text", type: "text", step: 2, body: "To solve equations like $x^2 = -1$, we introduce the imaginary unit $i$. This creates a completely new axis, perpendicular to the real numbers." },
      { id: "argand-step-2-math", type: "math", step: 2, expression: "i^2 = -1 \\implies i = \\sqrt{-1}", display: true },
      { id: "argand-step-3-heading", type: "heading", step: 3, text: "The Complex Plane", level: 2 },
      { id: "argand-step-3-text", type: "text", step: 3, body: "A complex number has a real part and an imaginary part. It exists as a specific coordinate $(a, b)$ in this 2D space, which we call the Argand Plane." },
      { id: "argand-step-3-math", type: "math", step: 3, expression: "z = a + bi", display: true },
      { id: "argand-step-3-interactive", type: "interactive", step: 3, provider: "custom", config: { visualizer: "argand-plane", z: { re: 3, im: 4 } } },
      {
        id: "argand-step-3-geogebra",
        type: "interactive",
        step: 3,
        provider: "geogebra",
        config: {
          visualizer: "geogebra",
          appName: "graphing",
          showToolbar: true,
          showAlgebraInput: false,
          showMenuBar: false,
          showResetIcon: true,
          height: 440,
        },
      },
      { id: "argand-step-4-heading", type: "heading", step: 4, text: "The Modulus", level: 2 },
      { id: "argand-step-4-text", type: "text", step: 4, body: "The modulus $|z|$ is simply the distance from the origin to the point $z$. By the Pythagorean theorem, this is $\\sqrt{a^2 + b^2}$." },
      { id: "argand-step-4-math", type: "math", step: 4, expression: "|z| = \\sqrt{3^2 + 4^2} = 5", display: true },
      { id: "argand-step-5-heading", type: "heading", step: 5, text: "The Argument", level: 2 },
      { id: "argand-step-5-text", type: "text", step: 5, body: "The argument $\\theta$ is the angle the vector makes with the positive real axis. Together, the modulus and argument give us the Polar Form." },
      { id: "argand-step-5-math", type: "math", step: 5, expression: "\\theta = \\tan^{-1}\\left(\\frac{4}{3}\\right) \\approx 53.1^\\circ", display: true },
      { id: "argand-step-5-question", type: "question", step: 5, questionId: "math151-argand-modulus-check" },
    ],
  },
  {
    id: "math151-cross-product",
    courseId: "math-151",
    chapterId: "vector-algebra",
    weekId: "math151-week-4",
    title: "The Cross Product",
    description: "Build a perpendicular vector from two vectors in 3D space and interpret the geometric meaning of its direction.",
    order: 4,
    estimatedMinutes: 20,
    objectives: [
      "Represent vectors in 3D space using components.",
      "Explain why the cross product produces a perpendicular vector.",
      "Use the right-hand rule to determine the direction of the result.",
    ],
    blocks: [
      { id: "cross-step-1-heading", type: "heading", step: 1, text: "Vectors in 3D Space", level: 2 },
      { id: "cross-step-1-text", type: "text", step: 1, body: "Unlike standard coordinate geometry, vectors possess both magnitude and direction. In a 3D coordinate system, a vector $\vec{v}$ can be represented by components in the $x$, $y$, and $z$ axes." },
      { id: "cross-step-1-math", type: "math", step: 1, expression: "\\vec{v} = x\\hat{i} + y\\hat{j} + z\\hat{k}", display: true },
      { id: "cross-step-2-heading", type: "heading", step: 2, text: "The Cross Product", level: 2 },
      { id: "cross-step-2-text", type: "text", step: 2, body: "The cross product of two vectors, $\vec{a} \times \vec{b}$, generates a completely new vector. It lives in 3D space and is inherently different from the scalar dot product." },
      { id: "cross-step-2-math", type: "math", step: 2, expression: "\\vec{c} = \\vec{a} \\times \\vec{b}", display: true },
      { id: "cross-step-2-interactive", type: "interactive", step: 2, provider: "custom", config: { visualizer: "cross-product", v1: [3, 0, 0], v2: [0, 2, 0], showResult: false } },
      { id: "cross-step-3-heading", type: "heading", step: 3, text: "Orthogonality", level: 2 },
      { id: "cross-step-3-text", type: "text", step: 3, body: "The most important property of the cross product is that the resulting vector is perpendicular to both original vectors. This means it defines a normal to the plane spanned by $\vec{a}$ and $\vec{b}$." },
      { id: "cross-step-3-math", type: "math", step: 3, expression: "\\vec{c} \\cdot \\vec{a} = 0 \\quad \\text{and} \\quad \\vec{c} \\cdot \\vec{b} = 0", display: true },
      { id: "cross-step-3-interactive", type: "interactive", step: 3, provider: "custom", config: { visualizer: "cross-product", v1: [3, 0, 0], v2: [0, 2, 0], showResult: true } },
      { id: "cross-step-4-heading", type: "heading", step: 4, text: "The Right-Hand Rule", level: 2 },
      { id: "cross-step-4-text", type: "text", step: 4, body: "The direction of $\vec{a} \times \vec{b}$ is determined by the right-hand rule. If your fingers curl from $\vec{a}$ to $\vec{b}$, your thumb points along the resulting cross product." },
      { id: "cross-step-4-interactive", type: "interactive", step: 4, provider: "custom", config: { visualizer: "cross-product", v1: [2, 1, 0], v2: [-1, 2, 0], showResult: true } },
    ],
  },
];
