import type { Question } from "../types/question";

export const math151Questions: Question[] = [
  {
    id: "math151-argand-modulus-check",
    courseId: "math-151",
    chapterId: "complex-numbers",
    lessonId: "math151-argand-plane",
    topic: "complex-numbers",
    subtopic: "modulus",
    type: "multiple-choice",
    prompt: "What is the modulus of z = 3 + 4i?",
    options: [
      { id: "a", label: "A", text: "3" },
      { id: "b", label: "B", text: "4" },
      { id: "c", label: "C", text: "5" },
      { id: "d", label: "D", text: "7" },
    ],
    correctAnswer: "c",
    explanation: "The modulus is the distance from the origin: $|z| = \sqrt{3^2 + 4^2} = 5$.",
    hint: "Use the Pythagorean theorem on the real and imaginary parts.",
    difficulty: "easy",
    marks: 1,
    tags: ["modulus", "complex-plane", "pythagorean-theorem"],
    metadata: { source: "authored", status: "published", author: "First Principles" },
  },
  {
    id: "math151-argand-argument-location",
    courseId: "math-151",
    chapterId: "complex-numbers",
    lessonId: "math151-argand-plane",
    topic: "complex-numbers",
    subtopic: "argument",
    type: "multiple-choice",
    prompt: "Which quadrant contains the complex number $z = -1 + i$?",
    options: [
      { id: "a", label: "A", text: "Quadrant I" },
      { id: "b", label: "B", text: "Quadrant II" },
      { id: "c", label: "C", text: "Quadrant III" },
      { id: "d", label: "D", text: "Quadrant IV" },
    ],
    correctAnswer: "b",
    explanation: "The real part is negative and the imaginary part is positive, so the point lies in Quadrant II.",
    hint: "Check the signs of the real and imaginary parts separately.",
    difficulty: "medium",
    marks: 2,
    tags: ["argument", "complex-plane", "quadrant"],
    metadata: { source: "authored", status: "published" },
  },
  {
    id: "math151-polar-form-conversion",
    courseId: "math-151",
    chapterId: "complex-numbers",
    lessonId: "math151-argand-plane",
    topic: "complex-numbers",
    subtopic: "polar-form",
    type: "multiple-choice",
    prompt: "Which polar form matches the complex number $z = 2\left(\cos\frac{\pi}{3} + i\sin\frac{\pi}{3}\right)$?",
    options: [
      { id: "a", label: "A", text: "$1 + i\sqrt{3}$" },
      { id: "b", label: "B", text: "$1 + i$" },
      { id: "c", label: "C", text: "$2 + 2i$" },
      { id: "d", label: "D", text: "$1 + 2i$" },
    ],
    correctAnswer: "a",
    explanation: "Since $\cos(\pi/3) = 1/2$ and $\sin(\pi/3) = \sqrt{3}/2$, multiplying by $2$ gives $1 + i\sqrt{3}$.",
    hint: "Distribute the modulus and use the standard trig values for $\pi/3$.",
    difficulty: "medium",
    marks: 2,
    tags: ["polar-form", "argument", "trigonometry"],
    metadata: { source: "authored", status: "published" },
  },
  {
    id: "math151-cross-product-direction",
    courseId: "math-151",
    chapterId: "vector-algebra",
    lessonId: "math151-cross-product",
    topic: "vector-algebra",
    subtopic: "cross-product",
    type: "multiple-choice",
    prompt: "The cross product $\vec{a} \times \vec{b}$ is always:",
    options: [
      { id: "a", label: "A", text: "A scalar" },
      { id: "b", label: "B", text: "A vector perpendicular to both $\vec{a}$ and $\vec{b}$" },
      { id: "c", label: "C", text: "Parallel to $\vec{a}$" },
      { id: "d", label: "D", text: "A point in space" },
    ],
    correctAnswer: "b",
    explanation: "The cross product of two vectors in 3D produces a new vector that is orthogonal to both input vectors.",
    hint: "Think of the normal vector to the plane formed by the two vectors.",
    difficulty: "easy",
    marks: 1,
    tags: ["cross-product", "vector-algebra", "orthogonality"],
    metadata: { source: "authored", status: "published" },
  },
  {
    id: "math151-dot-product-angle",
    courseId: "math-151",
    chapterId: "vector-algebra",
    lessonId: "math151-cross-product",
    topic: "vector-algebra",
    subtopic: "dot-product",
    type: "numerical",
    prompt: "If $\vec{u} = (3, 4)$ and $\vec{v} = (1, 2)$, what is $\vec{u} \cdot \vec{v}$?",
    correctAnswer: 11,
    explanation: "The dot product is $3\cdot1 + 4\cdot2 = 3 + 8 = 11$.",
    hint: "Multiply corresponding components and then add the results.",
    difficulty: "medium",
    marks: 2,
    tags: ["dot-product", "vector-algebra", "components"],
    metadata: { source: "authored", status: "published" },
  },
];
